doczjs/docz-website

src/docs/documentation/index.mdx
src/docs/introduction/index.mdx
src/docs/introduction/pages/customizing/index.mdx
src/docs/introduction/pages/documenting-your-things/index.mdx
src/docs/introduction/pages/getting-started/index.mdx
src/docs/introduction/pages/writing-mdx/index.mdx

This PR improves the documentation by fixing spell and gramatical errors, as well as with minor improvements on the documentation.

Fix introduction page wording on all sections

---

src/docs/documentation/pages/components-api/index.mdx

For me, an example of how to use variables is more clear than a description of how to use the variables.

Provide example of using variables in playground

---

docs/home/components/Features.tsx
docs/home/components/Sections.tsx

Some improvements to the copy of the home page, just to improve the readability.

Improve some of the copy in the home page to improve readability

---

src/docs/documentation/index.mdx
src/docs/documentation/pages/creating-themes/index.mdx
src/docs/home/components/Features.tsx
yarn.lock

I fixed a few typos on the website and clarified sentences that were unclear.

fixed spelling and grammar issues

---

docs/documentation/pages/project-configuration/index.mdx

Add missing `to` to TypeScript config description

Update TypeScript config description

---

docs/documentation/pages/creating-plugins/index.mdx

Update the `OnPreBuild` and `OnPostBuild` sections inside create-plugins documentation's page.

Update documentation based on v0.11.2

---

docs/introduction/pages/customizing/index.mdx

closes https://github.com/pedronauck/docz/issues/414#issuecomment-430324843

remove order from the docs

---

docs/documentation/pages/project-configuration/index.mdx

Add codeSandbox documentation for Project Configuration.
Cheers 🇧🇷!

docs: add codesandbox usage instructions

---

docs/documentation/pages/project-configuration/index.mdx

Updated documentation to better reflect the configuration options.

chore(docz-website): documentation updated

---

src/docs/documentation/general/getting-started.mdx

Hi! :wave: 
This PR just fixes a typo I caught while reading the Getting Started page.

Fix typo in the Getting Started page

---

doczrc.js

fix(favicon): Set `public` folder config and update favicon path

---

src/docs/documentation/general/deploying-your-docs.mdx

mention the netlify file name

---

src/docs/themes/components/Cards.tsx

Add Ztopia theme on website theme section :)

Add Ztopia theme

---

src/docs/documentation/references/project-configuration.mdx

Swapped `localhost:3000` for `www.docz.site`

Fix links to point to publicly accessible address

---

src/docs/documentation/references/project-configuration.mdx

Links were resolving to localhost

Fix broken links in Project Configuration

---

src/docs/documentation/general/document-settings.mdx

docs : fix broken link to create theme docs

---

src/docs/documentation/references/components-api.mdx

Doc related to https://github.com/doczjs/docz/pull/1371

docs: add useComponentProps doc

---

src/docs/documentation/general/getting-started.mdx

based on that change https://github.com/doczjs/docz/commit/1fc2bcffb82d098922b8c849c777986aacc700c1

chore(getting started): updates installing instructions

---

src/docs/documentation/general/document-settings.mdx

Documentation linked to this PR:
https://github.com/doczjs/docz/pull/1354

doc: add hidden part for document settings

---

src/docs/documentation/general/getting-started.mdx

Fixing small typo on the getting started page.

tiny: fix a small typo
