doczjs/docz-website

README.md, src/docs/home/components/HowTo.tsx
If docz is installed locally (as the first step in the How To assumes), you need to run it with either `npx` or `yarn` for the command to work. Added this to the frontpage. 
Also included the port for localhost in README, because it took me a minute to figure it out :)
=> How to: docz needs yarn to run

docs/introduction/pages/getting-started/index.mdx
I was create a example for my post with docz and create-react-app, but when tried to put in package.json the ```"dev": "docz dev"``` and ```"build": "docz build"```, i saw that there are the same commands to execute the project create-react-app. 
I believe that this problem happens to other people, so this pull request is to avoid future problems.
Thanks
=> fix(getting-started): change commands to put in package.json

docs/documentation/pages/components-api/index.mdx
This adds a paragraph and example code on how to add prop descriptions when using the `<PropsTable />` component.
=> Add prop description documentation

docs/introduction/index.mdx, docs/introduction/pages/customizing/index.mdx, docs/introduction/pages/deploying-your-docs/index.mdx, docs/introduction/pages/documenting-your-things/index.mdx, docs/introduction/pages/getting-started/index.mdx, docs/introduction/pages/writing-mdx/index.mdx
Fixed some grammar and clarified things that were unclear.
Common themes:
- Case consistency ("Title Case" vs "Sentence case")
- Fix [comma splices](https://en.wikipedia.org/wiki/Comma_splice)
- Avoid the word [very](https://ruthlesseditor.com/the-very-wise-avoid-very/)
=> Improve wording in Introduction

docs/introduction/pages/documenting-your-things/index.mdx
Currently the Button is a named export [here](https://www.docz.site/introduction/writing-mdx) whereas it is a default export [here](https://www.docz.site/introduction/documenting-your-things)
This PR makes all of them named export.
=> Make button import consistent with writing mdx section

docs/introduction/pages/customizing/index.mdx
It took me a bit to figure out how `modifyBundlerConfig` was supposed to work, so I thought I'd write down what I learned to help future Docz users. This provides an example that I think will be a commonly desired use case (adding a Webpack plugin).
=> docs: add an explanation of modifyBundlerConfig

docs/home/components/HowTo.tsx
Right now the instructions on the homepage are not sufficient to setup docz. Fixed it in this PR
=> Fixed the how-to example

src/docs/home/components/HowTo.tsx
`yarn Docz dev` is not a valid command, so lowercasing `docz` fixes that and communicates this on the home page of docz.site. 💻
=> fix: lowercase docz for valid homepage command

src/docs/documentation/general/customizing.mdx, src/docs/documentation/references/creating-themes.mdx, src/docs/documentation/references/project-configuration.mdx, src/docs/themes/components/Cards.tsx
The link to the GitHub repo for the default theme in several pages is wrong.  This corrects it.
Closes #54
=> feat(themes): fixing default theme's GitHub link

src/docs/documentation/references/gatsby-theme.mdx
The former Gatsby Themes URL was 404'ing. This PR updates to the new URL: https://www.gatsbyjs.org/docs/themes/introduction/
=> docs: fix broken Gatsby Themes link

src/docs/documentation/references/creating-themes.mdx
These two examples used a mix of the old and new API: importing ComponentsProvider, but rendering DocPreview. Also, `children` was undefined.
=> Add missing children param and use ComponentsProvider, not DocPreview

src/docs/documentation/references/components-api.mdx
It was not clear from the docs that the parameter of `useMenus` is an object, not a string.
Before (today):
With this change:
I also tried to clarify that it does not search in page content, only in the menu headers.
Also fixed a typo: "of" -> "or"
=> Clarify useMenus param in docs

src/docs/documentation/references/creating-themes.mdx, src/docs/documentation/references/project-configuration.mdx
I have found the theme path config documentation to be a bit confusing, and it seems I am not the only one. https://github.com/pedronauck/docz/issues/856
I felt like an example project structure would really help in seeing how things are connected. So this PR adds an example file structure on the Project Configuration and Creating Themes pages.
=> Improve doc for theme path using file structure examples

src/docs/documentation/references/project-configuration.mdx
I noticed that a markdown file was being included in my docz build... The documentation does not match the [source code](https://github.com/pedronauck/docz/blob/c0749d32d9b806b8a83fb91f0dbb34203585df4f/core/docz-core/src/config/argv.ts#L119).
Looking at the other options, there are other discrepancies: I'm not sure whether these just need to be fixed in the documentation, or if there's some other code that produces the documented behavior: (comparing [argv.ts](https://github.com/pedronauck/docz/blob/c0749d32d9b806b8a83fb91f0dbb34203585df4f/core/docz-core/src/config/argv.ts) to [project-configuration.mdx](https://github.com/pedronauck/docz-website/blob/2189a1b559a2cdc44b3fa5cb79fa729154ddd3aa/src/docs/documentation/references/project-configuration.mdx))
```
default: getEnv('docz.ignore', …
```
=> .md files are also included by default

src/docs/documentation/references/gatsby-theme.mdx
Fixing a few typos and sentence structure to make the documentation clearer for a native English speaker.
Please get in touch if you have any questions.
=> fix typos to gatsby theme documentation

src/docs/documentation/general/getting-started.mdx
When working through the Getting Started example, I had to specify `route: /` in the mdx frontmatter. Without it I was presented with the Gatsby 404 page when running the dev server.
docz version: `2.0.0-rc.38`
=> FIX: update getting started page to include a route

doczrc.js, src/docs/documentation/general/built-in-components.mdx, src/docs/documentation/general/writing-mdx.mdx
docs: correct inconsistent usage of built-ins-components vs built-in-components in favor of later to fix link from `usage-with-typescript.md`.
note: this will break external linking to https://www.docz.site/docs/built-ins-components but seems necessary since it should be https://www.docz.site/docs/built-in-components
=> docs: change `built-ins-components` => `built-in-components`

src/docs/home/components/Hero.tsx
The GitHub link was still pointing to the old repo address.
=> Update GitHub link

src/docs/documentation/customizing/add-favicon-and-metadata.mdx
This commit updates the documentation to recommend `react-helmet-async`
instead of `react-helmet`, as well as a note about why.
It looks like this:
Should be merged after this: https://github.com/doczjs/docz/pull/1223
=> docs: use react-helmet-async instead of react-helmet

src/docs/documentation/customizing/gatsby-theme.mdx
I believe the correct key here is `initialColorMode` per https://theme-ui.com/theme-spec/#color-modes
=> docs: update theme-ui initialColorMode key

src/docs/documentation/customizing/gatsby-theme.mdx
If you skip the index, it just imports undefined. That way we ensure the correct theme/file is imported.
=> docs(gatsby-theme): set correct import of base theme

src/docs/documentation/references/migration-guide.mdx
Incorrect filename listed in the code comment. Using `index.js` replaces the entire theme.
=> Fix filename in code comment

src/docs/documentation/general/built-in-components.mdx
Hello!
Thanks for this awesome library that is Docz. 
I couldn't find any doc about how to play with stateful components inside the `<Playground>` component. It seems that I was not the only one wondering this: see https://github.com/doczjs/docz/issues/567.
This PR adds a section in the docs of the built-in's playground to show how one can use a stateful and functional component inside the `<Playground>` element.
=> Feat: add stateful section to playground docs

src/docs/documentation/customizing/gatsby-theme.mdx
This link (`https://github.com/doczjs/docz/blob/feat/gatsby/core/gatsby-theme-docz/src/theme/index.js`) currently leads to a 404:
It appears that the base config object now lives at: https://github.com/doczjs/docz/blob/master/core/gatsby-theme-docz/src/theme/index.js
=> docs: fix broken link to the base theme object
